### ISSUE TITLE
Install Script Not Availebl

### ISSUE THREAD

**Issue by sgoodgrove** [technomancy/leiningen.org#15]
I get no response when attempting to download leiningen either via [leiningen.org](http://leiningen.org) or via chocolatey. The URL on the homepage is https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat (bash file also fails).

The chocolatey message is

    Downloading from https://raw.githubusercontent.com/technomancy/leiningen/2.7.1/bin/lein.bat
    Attempt to get headers for https://raw.githubusercontent.com/technomancy/leiningen/2.7.1/bin/lein.bat failed.
      The remote file either doesn't exist, is unauthorized, or is forbidden for url https://raw.githubusercontent.com/technomancy/leiningen/2.7.1/bin/lein.bat'. Exception calling GetResponse" with "0" argument(s): "Unable to connect to the remote server"
    Downloading Leiningen
      from 'https://raw.githubusercontent.com/technomancy/leiningen/2.7.1/bin/lein.bat'
    ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url https://raw.githubusercontent.com/technomancy/leiningen/2.7.1/bin/lein.bat'. Exception calling GetResponse" with "0" argument(s): "Unable to connect to the remote server"
    The install of lein was NOT successful.
    Error while running 'C:\ProgramData\chocolatey\lib\Lein\tools\chocolateyInstall.ps1'.
    See log for details.

I have instead installed via the leiningen installer from the homepage.

**Comment by hyPiRion** [comment]
Could you try again now? `"Unable to connect to the remote server"` typically means there were some issues with GitHub's servers, and the link works fine from here.

**Comment by sgoodgrove** [comment]
Ah ok. Thanks for confirming. I tested again and got the same no response. Tested again on http instead of https and I got a “blocked” message from my ISP (Sky UK). I’ve been into my ISP and added the domain to the “allowed” list and now all is good.

**Comment by technomancy** [comment]
> Tested again on http instead of https and I got a “blocked” message from my ISP

Even if you hadn't been blocked by your ISP, the http-only download would not have worked; it always redirects to HTTPS. Downloading without HTTPS is a very bad idea; please don't do it.

**Comment by sgoodgrove** [comment]
Agreed... but HTTP was the way that I was able to diagnose the issue at my end as HTTP and HTTPS behaved differently.
