### ISSUE TITLE
Install Paragraph is Bad

### ISSUE THREAD

**Issue by JimTheMan** [technomancy/leiningen.org#8]
Hi. I'm following the "Install" paragraph. I download the text file and ran `mv lein.txt ~/bin`

Then I went to run the next command, `chmod a+x ~/bin/lein`, and it said file not found.

Thy is this install guide a cryptic puzzle for getting set up? It should be more straightforward and give examples. Describing what to do in hazy, terse statements that can't be easily followed is a great way to turn off potential new users and make everyone say, "wow leiningen is a piece of garbage".

I don't think that. I'm just saying that is what the "Install" block of this guide makes people think. All people, every time. It's just a relly, really bad guide. No offense.

**Comment by technomancy** [comment]
I dunno; if you don't know how to save a file to a specified location on your disk, maybe Leiningen isn't right for you.

**Comment by JimTheMan** [comment]
It's not just saving the file (although you are correct that the link was incorrectly implemented. It redirects to a page of text instead of downloading the file). After looking up "how to place a file in your PATH" I think I am on the right track.

Still, for the sake of making Clojure more popular you should think about whether the installation guide is meant to appeal to experienced superusers like yourself or to complete beginners who know nothing about using Clojure and are starting here since after all Leiningen claims to be, "Leiningen is the EASIEST way to use Closure". 

I'm just trying to give you a fresh perspective from a beginner with Leiningen, and IMO it could be much more approachable than it currently is.

**Comment by JimLynchCodes** [comment]
Hey @technomancy!

Sorry to dig up this old post, but I was just setting up leiningen on a new computer, and I can't help but be disappointed by how much more involved the installation process is compared with every other cli tool available these days...

It would be really awesome if we could just do `brew install leiningen` or `npm i -g leiningen`. 

Not trying to be a jerk here (I was more of a troll back in the day, but I have changed now 😅).

I'm sure you have been using Clojure for years and years and years, but keep in mind that there are people being born all the time and every day _there are new people learning Clojure for the first time!_

Personally, I think having an installation process that amounts to just running one single command would be incredibly beneficial to newcomers, to Leiningen, and to the entire Clojure / ClojureScript ecosystem.

I can help out with this if you think it is a good idea.

I really appreciate everything you've done here and am just trying to help it become even better. 🙏

**Comment by JimLynchCodes** [comment]
Lol wow I'm so dumb. We already can do `brew install leiningen` and so many other "easy" ways for us simpletons.

Thanks so much! Yay Clojure! ❤️
