### ISSUE TITLE
Site should use SSL/TLS by default

### ISSUE THREAD

**Issue by timmc** [technomancy/leiningen.org#9]
As a software distribution point, it would be great if leiningen.org used SSL/TLS by default! Here's what would need to happen:

- [x] Change font resources to load over HTTPS: https://github.com/technomancy/leiningen.org/pull/10
- [x] Change site to redirect to HTTPS
- [ ] Change links to leiningen.org (e.g. in its own project file)
- [x] Bonus: Update outbound links to HTTPS where possible: https://github.com/technomancy/leiningen.org/pull/11
- [x] Bonus: Use Strict-Transport-Security header (HSTS) to improve security further

**Comment by technomancy** [comment]
https://github.com/technomancy/leiningen/commit/4874c7bf0fa81d0ccf84c9a9979ea4af4483d18d should take care of this; thanks for opening the issue.

**Comment by timmc** [comment]
Wow, that's a lot of S's! Thanks. :-)
